export const QWEN_CODE_SETUP_CONTRACT = {
  packageName: "@gonkagate/qwen-code-setup",
  packageVersion: "0.1.0",
  publicEntrypoint: "npx @gonkagate/qwen-code-setup",
  binaryName: "gonkagate-qwen-code",
  binaryAliases: ["gonkagate-qwen-code", "qwen-code-setup"],
  stableProviderId: "gonkagate",
  canonicalBaseUrl: "https://api.gonkagate.com/v1",
  qwenPackageName: "@qwen-code/qwen-code",
  qwenBinaryName: "qwen",
  qwenPackageNodeEngine: ">=22.0.0",
  minimumNodeVersion: ">=22.14.0",
  latestAuditedQwenCodeVersion: "0.18.0",
  latestAuditedQwenCodeDate: "2026-06-12",
  latestAuditedQwenCodeVerdict: "CONCERNS",
  latestAuditedQwenCodeTag: "v0.18.0",
  latestAuditedQwenCodeTagCommit: "a7b8a3655c73c14dde99ab7138a566885e31c68f",
  runtimeImplemented: true,
  curatedRegistryPublished: true,
  requiredGonkagateModelCount: 3,
  qwenUserSettingsPath: "~/.qwen/settings.json",
  qwenHomeSettingsPath: "<QWEN_HOME>/settings.json",
  qwenWorkspaceSettingsPath: ".qwen/settings.json",
  qwenSystemSettingsPaths: [
    "/etc/qwen-code/settings.json",
    "/Library/Application Support/QwenCode/settings.json",
    "C:\\ProgramData\\qwen-code\\settings.json",
  ],
  qwenSystemSettingsPathEnvKey: "QWEN_CODE_SYSTEM_SETTINGS_PATH",
  qwenSystemDefaultsPathEnvKey: "QWEN_CODE_SYSTEM_DEFAULTS_PATH",
  qwenModelProvidersMergeStrategy: "replace",
  qwenAuthType: "openai",
  qwenAuthSelectedTypePath: "security.auth.selectedType",
  qwenActiveModelPath: "model.name",
  qwenEnvKey: "GONKAGATE_API_KEY",
  qwenDurableSecretPath: "settings.env.GONKAGATE_API_KEY",
  qwenEnvPrecedence: [
    "CLI flags",
    "process.env",
    "first .env file",
    "settings.env",
  ],
  qwenAuthCommandRemoved: true,
  qwenStatusSurface: "/doctor",
} as const;

export type QwenCodeSetupContract = typeof QWEN_CODE_SETUP_CONTRACT;
